import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { UIProvider, Button } from "@yamada-ui/react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <UIProvider>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/doc-entry">企画書・エントリー</Link>
          <Link href="/sche-info">スケジュール・お知らせ</Link>
          <Link href="/rule-example">例題・ルール詳細説明</Link>
          <Link href="/about">サークル・サークルキャラクター紹介</Link>
        </nav>
          {children}
        </UIProvider>
      </body>
    </html>
  );
}
